---
# tasks file for rsyslog
- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: manage ryslog
  block:

    - name: uninstall conflicting systemd-logger
      package:
        name: systemd-logger
        state: absent

    - name: install rsyslog
      package:
        name: "{{ rsyslog_packages }}"
        state: present

    - name: configuring rsyslog
      template:
        src: "{{ rsyslog_config_file_format }}_rsyslog.conf.j2"
        dest: /etc/rsyslog.conf
        mode: "0644"
      notify:
        - restart rsyslog

    - name: make configuration directory
      file:
        name: /etc/rsyslog.d/
        state: directory
        mode: "0755"

    - name: start and enable rsyslog
      service:
        name: "{{ rsyslog_service }}"
        state: started
        enabled: yes

  when: rsyslog_enable | bool
